export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

export const FETCH_CATEGORY_NEWS = "FETCH_CATEGORY_NEWS";
export const FETCH_CATEGORY_NEWS_SUCCESS = "FETCH_CATEGORY_NEWS_SUCCESS";
export const FETCH_CATEGORY_NEWS_FAILED = "FETCH_CATEGORY_NEWS_FAILED";

export const FETCH_NEWS_DETAILS = "FETCH_NEWS_DETAILS";
export const FETCH_NEWS_DETAILS_SUCCESS = "FETCH_NEWS_DETAILS_SUCCESS";
export const FETCH_NEWS_DETAILS_FAILED = "FETCH_NEWS_DETAILS_FAILED";